#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Pre-Push Tests..."

echo "Running Unit Tests..."
npm run test || { echo "Unit Tests failed. Push aborted."; exit 1; }

echo "Running E2E Tests..."
npm run test:e2e || { echo "E2E Tests failed. Push aborted."; exit 1; }

echo "All tests passed. Proceeding with push."
